
-- Stone Monster

mobs:register_mob("mobs:stone_monster", {
	type = "monster",
	hp_min = 30,
	hp_max = 35,
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
	textures = {"mobs_stone_monster.png"},
	visual_size = {x=3, y=2.6},
	makes_footstep_sound = true,
	view_range = 16,
	walk_velocity = 2,
	run_velocity = 4,
	damage = 5,
	drops = {
		{name = "default:torch",
		chance = 10,
		min = 3,
		max = 5,},
		{name = "default:iron_lump",
		chance = 5,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 3,
		min = 1,
		max = 3,},
		{name = "maptools:silver_coin",
		chance = 2,
		min = 2,
		max = 3,},
	},
	light_resistant = true,
	armor = 60,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 0,
	light_damage = 0,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	jump = true,
	step = 1,
	blood_texture = "mobs_blood.png",
})
mobs:register_spawn("mobs:stone_monster", {"default:stone", "nether:dirt_top"}, 3, -1, 5000, 1, 0)
