-- Fuel group --
treasurer.register_treasure("bucket:bucket_lava",0.008,3,1)
treasurer.register_treasure("default:coalblock",0.008,2,{1,2})
treasurer.register_treasure("default:wood",0.075,2,{1,15})
treasurer.register_treasure("default:tree",0.07,2,{1,5})
treasurer.register_treasure("default:cactus",0.06,{1,7})
treasurer.register_treasure("homedecor:oil_extract",0.02,2,{1,20})
treasurer.register_treasure("default:grass_1",0.09,2,{1,30})
treasurer.register_treasure("default:leaves",0.099,2,{1,20})
treasurer.register_treasure("default:junglegrass",0.085,2,{1,20})
treasurer.register_treasure("default:dry_shrub",0.085,2,{1,10})

-- Food group --
treasurer.register_treasure("food:bowl",0.07,2,1)
treasurer.register_treasure("food:milk",0.075,2,1)
treasurer.register_treasure("bushes:mixed_berry_pie_raw",0.06,2,{1,3})
treasurer.register_treasure("bushes:blackberry_pie_raw",0.064,2,{1,4})
treasurer.register_treasure("bushes:blueberry_pie_raw", 0.064,2,{1,4})
treasurer.register_treasure("bushes:strawberry_pie_raw", 0.064,2,{1,4})
treasurer.register_treasure("bushes:raspberry_pie_raw", 0.064,2,{1,4})
treasurer.register_treasure("farming:bread", 0.07,2,{1,2})
treasurer.register_treasure("farming:flour", 0.075,2,{1,3})
treasurer.register_treasure("farming:carrot", 0.071,2,{1,4})
treasurer.register_treasure("farming:donut", 0.068,2,{1,3})
treasurer.register_treasure("farming:melon_slice", 0.074,2,{1,6})
treasurer.register_treasure("farming:tomato", 0.075,2,{1,6})
treasurer.register_treasure("fishing:fish_raw", 0.063,2,{1,2})
treasurer.register_treasure("maptools:superapple", 0.002,2,1})
treasurer.register_treasure("mobs:chicken_raw", 0.060,2,{1,4})
treasurer.register_treasure("mobs:meat_raw", 0.065,2,{1,4})
treasurer.register_treasure("moretrees:coconut", 0.055,2,{1,2})
treasurer.register_treasure("mushroom:poison", 0.059,2,{1,5})
treasurer.register_treasure("farming:blueberries", 0.05,2,{1,10})

-- Melee weapons --
treasurer.register_treasure("building_blocks:knife", 0.045,2,1})
treasurer.register_treasure("moreores:sword_silver", 0.0002,2,1})
treasurer.register_treasure("nether:sword_sywtonic", 0.0001,2,1})
treasurer.register_treasure("nether:sword_netherrack_blue", 0.001,2,1})
treasurer.register_treasure("nether:sword_netherrack", 0.001,2,1})
treasurer.register_treasure("default:sword_nyan", 0.0000121,1})


-- Tools --
treasurer.register_treasure("default:axe_nyan", 0.0000121,1})
treasurer.register_treasure("default:shovel_nyan", 0.000121,1})
treasurer.register_treasure("default:pick_nyan", 0.000121,1}
treasurer.register_treasure("default:hoe_wood", 0.02, 1})
treasurer.register_treasure("default:hoe_stone", 0.004,1})
treasurer.register_treasure("default:hoe_steel", 0.002,1})
treasurer.register_treasure("default:hoe_bronze", 0.0008,1})
treasurer.register_treasure("default:hoe_mese", 0.0002, 1})
treasurer.register_treasure("default:hoe_diamond", 0.000121,1})
treasurer.register_treasure("fishing:pole", 0.05, 1})
treasurer.register_treasure("markers:mark", 0.034, 1})
treasurer.register_treasure("moreores:axe_silver", 0.0001, 1})
treasurer.register_treasure("moreores:hoe_silver", 0.00013, 1})
treasurer.register_treasure("moreores:pick_silver", 0.00009, 1})
treasurer.register_treasure("moreores:shovel_silver", 0.00014, 1})
treasurer.register_treasure("screwdriver:screwdriver", 0.001, 1})
treasurer.register_treasure("moreblocks:circular_saw", 0.002, 1})

-- Deco group --
treasurer.register_treasure("bobblocks:redblock", 0.02, {1,5})
treasurer.register_treasure("bobblocks:greypole", 0.02, {1,5})
treasurer.register_treasure("coloredwood:fence_light_sky_blue", 0.025, {1,6})
treasurer.register_treasure("coloredwood:fence_dark_redviolet", 0.025, {1,6})
treasurer.register_treasure("coloredwood:stick_dark_cyan", 0.02, {1,4})
treasurer.register_treasure("coloredwood:fence_yellow", 0.025, {1,6})
treasurer.register_treasure("colouredstonebricks:brown", 0.03, {1,10})
treasurer.register_treasure("colouredstonebricks:yellow", 0.03, {1,10})
treasurer.register_treasure("darkage:chain", 0.025, {1,10})
treasurer.register_treasure("columnia:column_mid_brick", 0.025, {1,7})
treasurer.register_treasure("darkage:wood_shelves", 0.02, {1,2})
treasurer.register_treasure("default:fence_cobble", 0.03, {1,20})
treasurer.register_treasure("dryplants:grass", 0.04, {1,8})
treasurer.register_treasure("fake_fire:embers", 0.015, {1,3})
treasurer.register_treasure("fence:fencegate", 0.02, {1,2})
treasurer.register_treasure("flowers:potted_tulip", 0.02, {1,4})
treasurer.register_treasure("itemframes:pedestal_junglewood", 0.012, {1,3})
treasurer.register_treasure("lantern:candle", 0.03, {1,15})
treasurer.register_treasure("lavatemple:ladder", 0.018, {1,8})
treasurer.register_treasure("moreblocks:plankstone", 0.025, {1,6})
treasurer.register_treasure("moreblocks:iron_check", 0.02, {1,3})
treasurer.register_treasure("stained_glass:2_9", 0.02, {1,4})
treasurer.register_treasure("stained_glass:7_5_6", 0.02, {1,4})


